spring.application.name=CricketMatchSimulator

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27018
spring.data.mongodb.database=cricket_match_simulator
spring.data.mongodb.auto-index-creation=true